### PR TITLE
Some comments on the first pass

### PR DESCRIPTION
**Pull request by gvwilson**
I've also added `*~` to `.gitignore` to ignore my Emacs backup files.

### CODE REVIEW

**Comment by LJWilliams** [comment]
Can I reopen this? #2

**Comment by gvwilson** [comment]
Yes.

**Comment by gvwilson** [comment]
OK - what three things do you understand now that your younger self didn't?

**Comment by LJWilliams** [comment]
On Jan 14, 2017, at 11:49 AM, Greg Wilson <notifications@github.com> wrote:

> OK - what three things do you understand now that your younger self didn’t?

1. Unlike in math stuff, you don’t need to ‘save space’ for variables, especially if you aren’t keeping them around (i.e., don’t initialize something you don’t need)
2. Keep it simple — don’t have a bunch of statements that could/should be done by some other class (if you are doing 2 things you are doing too much) — also don’t waste time trying to build stuff you don’t have to
3. Parent child relationships should be clear — if all the children don’t need something, they shouldn’t inherit it
and an extra one:
4. iterators should be used judiciously — if you don’t need to repetitively increment values from within a loop (an index, record, etc.), you don’t need an iterator in your class

Thanks Greg

**Comment by LJWilliams** [comment]
Plus a reminder:

Think before you code. 
	Just because something seems simple, it should be thought through first.

Talk to you on Monday.

Lynne

**Pull request merged**
